[context.production.environment]
  HUGO_VERSION = "0.122.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[build]
  publish = "static"
  command = "hugo --gc --minify"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.122.0"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/npmjs/*"
  to = "/npmjs/"
  status =  200